AdrKacz/super-duper-guacamole

README.md, awa-web/package.json, awa-web/src/hooks/useMessages.js, awa/App.js, awa/index.js, awa/ios/fastlane/.gitignore, awa/package.json, awa/src/hooks/useMessages.js, awa/yarn.lock
Simplify code and uniformise message format for web and app
Check that messages work with Android and iOS
Change PUT to SET
*(seem to help to keep message in memory for an unknown reason)*
=> Update Awa App and Web

.github/workflows/fastlane.yml, README.md
Pour ne pas build à chaque Merge to Main
=> Update Fastlane Lauch

README.md
Just add Codebase description to README so we can keep track of how complex is the code 👨‍💻
=> Add codebase

ROADMAP.md
J'ai ajouté ROADMAD avec Mermaid au projet. Impossible de l'ajouter au Wiki (ne supporte pas encore Mermaid il faut croire 😢)
⚠️ Il ne faut pas MERGE, comme tu peux voir elle est **loin** d'être complète, c'est juste une *placeholder*.
=> Add exemple Roadmap

ROADMAP.md, recommender-system/.gitignore, recommender-system/README.md, recommender-system/app.py, recommender-system/model-x/app.py, recommender-system/test.py
Friday Code - Connexion between AWS Lambdas working
=> Recommender system

PRIVACY_POLICY.md, awa-chat-flutter/awachat/README.md, privacy-policy/README.md, privacy-policy/en, privacy-policy/fr
=> privacy policy update

README.md, awa-chat-flutter/awachat/ios/Podfile.lock, awa-chat-flutter/awachat/lib/main.dart, awa-chat-flutter/awachat/pubspec.lock, awa-chat-flutter/awachat/pubspec.yaml
Reconnection à la conversion en cours après avoir fermé l'application.
- `user-id` est redéfinie à chaque ouverture de l'application (donc nos anciens messages sont attribués à `other`)
- Si l'application se met en `background`/`veille`, le script de `init` ne se lance pas et donc la reconnection ne fonctionne pas (il faut fermer et réouvrir l'application)
=> Reconnection to existing room working

awa-chat-flutter/awachat/lib/WebSocketConnection.dart, awa-chat-flutter/awachat/lib/main.dart, awa-chat-flutter/awachat/lib/message.dart, awa-chat-flutter/awachat/lib/notificationhandler.dart
On peut maintenant voir quand le message est entrain de s'envoyer et a été envoyé 😎
=> ~~Read stream from notification~~ Add message status

awa-chat-flutter/awachat/lib/WebSocketConnection.dart, awa-chat-flutter/awachat/lib/main.dart
L'app se reconnecte automatiquement lors d'une déconnexion.
L'utilisateur est automatique déconnecté quand il place l'app dans le background (permet de compter qui est ACTIVEMENT sur la conversation)
=> Add Blur on deconnection reconnection

agreements/credits/fr, awa-chat-flutter/awachat/lib/main.dart, awa-chat-flutter/awachat/lib/widgets/agreements.dart, awa-chat-flutter/awachat/lib/widgets/error.dart, awa-chat-flutter/awachat/lib/widgets/glass.dart, awa-chat-flutter/awachat/lib/widgets/loader.dart, awa-chat-flutter/awachat/lib/widgets/switch_group.dart, awa-chat-flutter/awachat/lib/widgets/user_drawer.dart
**CETTE PR VIENT APRÈS #96 et #101**
J'ai rajouté un encart pour afficher les droits de license qu'on utilise. *Rendons à César ce qui lui appartient**.
=> Add a copyright on the work we use

awa-chat-flutter/awachat/lib/application_theme.dart, awa-chat-flutter/awachat/lib/main.dart, awa-chat-flutter/awachat/lib/widgets/agreements.dart, awa-chat-flutter/awachat/lib/widgets/custom_chat.dart, awa-chat-flutter/awachat/lib/widgets/error.dart, awa-chat-flutter/awachat/lib/widgets/glass.dart, awa-chat-flutter/awachat/lib/widgets/loader.dart, awa-chat-flutter/awachat/lib/widgets/presentation.dart, awa-chat-flutter/awachat/lib/widgets/questions.dart, awa-chat-flutter/awachat/lib/widgets/switch_group.dart, awa-chat-flutter/awachat/lib/widgets/user_drawer.dart, awa-chat-flutter/awachat/lib/widgets/users_list.dart
Tu peux maintenant changer toutes les couleurs de l'application au même endroit.
Plus tard, on définira aussi la *font* ici (pour l'instant j'utilise celle par défaut).
```dart
// ===== ===== =====
// Colors
const primary = Color(0xff6f61e8);
const secondary = Color(0xfff5f5f7);
const black = Color(0xff1f1c38);
const grey = Color(0xff9e9cab);
// ===== ===== =====
// Themes
final applicationTheme = ThemeData(
disabledColor: grey,
colorScheme: ColorScheme(
brightness: Brightness.light,
// main action
primary: secondary,
onPrimary: primary,
// other action
secondary: secondary,
onSecondary: black,
// active status
tertiary: Colors.green,
// error
error: Colors.white,
onError: Colors.redAccent.shade100,
// not used
background: Colors.transparent,
onBackground: Colors.transparent,
surface: …
```
=> add a theme to the app

README.md, questions/fr.yaml
Questions pour catégoriser les gens et les mettre dans un bon groupe. Besoin d'un changement car actuellement, les utilisateurs ne pourront pas se rencontrer donc certaines des questions n'étaient plus vraiment pertinentes.
=> Changement des questions

chat-application/lib/main.dart, chat-backend/.dependencies/aws-sdk-api/nodejs/package-lock.json, chat-backend/.dependencies/aws-sdk-ddb/nodejs/package-lock.json, chat-backend/.dependencies/aws-sdk-sns/nodejs/package-lock.json, chat-backend/.dependencies/firebase-admin/nodejs/package-lock.json, chat-backend/actions/ondisconnect/app.js, chat-backend/actions/register/app.js, chat-backend/handle-inactive-users/app.js, chat-backend/handle-inactive-users/helpers.js, chat-backend/sendmessage/app.js, chat-backend/switchgroup/app.js
**Fix bugs**
- I didn't notify a user when another user leave the group
- I was updating the user after its deletion, so it was re-create
I removed the `isActive` flag in the database because it is just a duplicate of `connectionId`. If the user is connected, its `connectionId` is **not** null.
=> Auto delete users doesnt work

chat-application/ios/Podfile.lock, chat-application/lib/widgets/user_drawer.dart, chat-application/pubspec.lock, chat-backend/.dependencies/aws-sdk-api/nodejs/package-lock.json, chat-backend/.dependencies/aws-sdk-ddb/nodejs/package-lock.json, chat-backend/.dependencies/aws-sdk-sns/nodejs/package-lock.json, chat-backend/.dependencies/firebase-admin/nodejs/package-lock.json
Just add a contact information button
https://user-images.githubusercontent.com/61620013/174475288-c3830416-5e4f-4740-8527-d092404d5ce1.mov
=> Add contact information

README.md
Was aiming to the wrong build
Signed-off-by: AdrKacz <61620013+AdrKacz@users.noreply.github.com>
=> Edit CodeMagic Badge

README.md
J'ai ajouté CodeScene en tant que *External Service*, il vérifie que le code ne sot pas compliqué à lire et à modifier dans le futur.
Signed-off-by: AdrKacz <61620013+AdrKacz@users.noreply.github.com>
=> Add new external service

chat-backend/samconfig.toml, chat-backend/template.yaml
J'ai modifié le fichier **SAM** pour avoir une limit du nombre de requête par défaut (sans avoir besoin de le modifier à la main dans AWS).
=> Add Rate Limit by default

chat-application/ios/fastlane/metadata/fr-FR/marketing_url.txt
Short update to just update the marketing URL.
=> add apple marketing url

.github/workflows/release-app.yml, chat-application/android/Gemfile.lock, chat-application/ios/Gemfile.lock
Update `gemfile` to be up to date with the Github Action version (not sure what the problem was, but it solved it).
Change working directory (action was trying to run in the wrong directory, this was never fired because of the error above btw)
=> 226 auto publish doesnt work

.github/workflows/verify-code-version.yml, codemagic.yaml
=> Correct CodeMagic

chat-application/android/fastlane/metadata/android/fr-FR/changelogs/default.txt, chat-application/ios/fastlane/metadata/fr-FR/release_notes.txt
Changelog ne contenait pas la possibilité de *report* les photos.
=> 240 update text not correct

.github/CODEOWNERS, .github/workflows/sam-pipeline.yml, chat-backend/README.md, chat-backend/package.json
Add Codeowners file to be automatically notified on PR.
=> Add CODEOWNERS

.vscode/launch.json, chat-backend/actions/register/__tests__/app.test.js, chat-backend/actions/register/app.js
Change variable name for clarity
=> Rename Group to GroupId in Register Function

chat-backend/actions/switchgroup/app.js, chat-backend/switchgroup/app.js, chat-backend/template.yaml
Rename to GroupId
I change a secondary index, cannot be done automatically, so backend is already updated.
=> rename: group to groupid in switchgroup

chat-backend/README.md, chat-backend/template.yaml
Index User by Group Id to search users in a group
=> Add GroupIdIndex to User Table

chat-backend/.well-known/openid-configuration, chat-backend/http/put/sign-in/__tests__/app.test.js, chat-backend/http/put/sign-in/app.js, chat-backend/samconfig.toml, chat-backend/template.yaml
=> fix: update url to OAuth issuer

.github/workflows/sam-pipeline.yml
Don't skip-ci. Need to do CI to install packages.
=> Add ci to SAM Pipeline

chat-backend/template.yaml
Share profile need to update user item to store unread message.
=> fix: update policy from read to crud

chat-application/README.md, chat-application/ios/Flutter/Debug.xcconfig, chat-application/ios/Flutter/Release.xcconfig, chat-application/ios/Podfile.lock, chat-application/ios/Runner.xcodeproj/project.pbxproj, chat-application/ios/Runner/Info.plist, chat-application/lib/store/user.dart, chat-application/lib/widgets/chat/main.dart, chat-application/lib/widgets/chat/widgets/users_list.dart, chat-application/pubspec.lock, chat-application/pubspec.yaml
=> Update application dependencies

chat-application/lib/store/user.dart, chat-application/lib/widgets/chat/main.dart, chat-application/lib/widgets/chat/widgets/user_drawer.dart
feat: remove reinit user feature
=> feat: remove reinit user feature

chat-application/lib/widgets/cities/cities_loader.dart
=> fix: update city url from feature branch to main

chat-application/lib/message.dart, chat-application/lib/store/memory.dart, chat-application/lib/store/user.dart, chat-application/lib/widgets/cities/cities_loader.dart
Il y a des block mémoire qui ne sont plus utilisé, pour être sur de n'avoir aucun problème j'ai tout viré du code.
=> 339 delete memory boxes not used

chat-application/lib/widgets/presentation.dart
Difficult de trouver les mots juste pour expliquer qu'on ne peut être que dans un groupe à la fois sans que ça sonne comme un problème, une limitation, ou bien encore un moralisateur "si je te donne plus tu vas parler à tout le monde et voir personne" 🥲
=> feat/ update text in onboarding

chat-application/lib/store/user.dart, chat-application/lib/widgets/chat/main.dart
Explication dans le thread associé.
Je unlink la PR pour qu'elle ne ferme pas l'issue car ce n'est pas terminé, c'est juste une petite step.
=> fix: await for reset group

.github/workflows/verify-code-version.yml
Unrelated to initial change, just a problem I encounter
=> fix: condition for verify code version

chat-backend/chat-backend-package/package-lock.json, chat-backend/chat-backend-package/src/__tests__/disconnect-user.test.js, chat-backend/chat-backend-package/src/disconnect-user.js, chat-backend/chat-backend-package/src/helpers/send-message.js, chat-backend/http/delete/unread-data/package-lock.json, chat-backend/http/get/status/package-lock.json, chat-backend/http/post/change-group/package-lock.json, chat-backend/http/put/firebase-token/package-lock.json, chat-backend/http/put/reply-ban/package-lock.json, chat-backend/http/put/request-ban/package-lock.json, chat-backend/http/put/sign-in/package-lock.json, chat-backend/http/put/sign-up/package-lock.json, chat-backend/manual-setup/package-lock.json, chat-backend/manual-setup/yarn.lock, chat-backend/package-lock.json, chat-backend/websocket/authorizer/package-lock.json, chat-backend/websocket/on-connect/package-lock.json, chat-backend/websocket/on-disconnect/__tests__/app.test.js, chat-backend/websocket/on-disconnect/app.js, chat-backend/websocket/on-disconnect/package-lock.json, chat-backend/yarn.lock
J'ai mis la function `disconnectUser` dans les helpers, au lieu d'être simplement appelé lors d'une déconnection, qui peut être loupé, elle est aussi appelé à chaque erreur d'envoie de message a une certaine connection. Si il y a erreur c'est que la connection n'est plus valide donc on enlève, et le status sera bien à jour.
Je ne fais pas *que* enlevé parce qu'il faut aussi alerter les users connecté du membre parti, c'est pourquoi j'outsource dans les helpers pour éviter la duplication de code.
=> 371 utilisateur marqué comme connecté alors qu'il ne l'est pas

chat-application/ios/Podfile, chat-application/ios/Podfile.lock, chat-application/ios/Runner/Info.plist, chat-application/lib/main.dart, chat-application/lib/store/user.dart, chat-application/lib/widgets/avatar.dart, chat-application/lib/widgets/chat/main.dart, chat-application/lib/widgets/chat/widgets/user_drawer.dart, chat-application/lib/widgets/chat/widgets/users_list.dart, chat-application/lib/widgets/cities/cities_loader.dart, chat-application/lib/widgets/upload_photo.dart, chat-application/pubspec.lock, chat-application/pubspec.yaml
You can take a picture, it will display in your profile, it is not shared for now
=> 373 can take a picture and use it as profile picture

codemagic.yaml
=> fix: temp force app build number

codemagic.yaml
=> fix: revert force build number

.github/workflows/sam-pipeline.yml, chat-backend/chat-backend-package/package-lock.json, chat-backend/http/delete/unread-data/package-lock.json, chat-backend/http/get/status/package-lock.json, chat-backend/http/post/change-group/package-lock.json, chat-backend/http/post/download-user/package-lock.json, chat-backend/http/post/upload-user/package-lock.json, chat-backend/http/put/firebase-token/package-lock.json, chat-backend/http/put/reply-ban/package-lock.json, chat-backend/http/put/request-ban/package-lock.json, chat-backend/http/put/sign-in/package-lock.json, chat-backend/http/put/sign-up/package-lock.json, chat-backend/manual-setup/package-lock.json, chat-backend/manual-setup/yarn.lock, chat-backend/package.json, chat-backend/scripts/install/install-package.sh, chat-backend/scripts/install/install.sh, chat-backend/scripts/npm-multiple-folders.sh, chat-backend/scripts/pre-deploy/predeploy-package.sh, chat-backend/scripts/pre-deploy/predeploy.sh, chat-backend/scripts/upgrade/upgrade-package.sh, chat-backend/scripts/upgrade/upgrade.sh, chat-backend/websocket/authorizer/package-lock.json, chat-backend/websocket/on-connect/package-lock.json, chat-backend/websocket/on-disconnect/package-lock.json
Will be detach from the original Issues to continue research
=> fix: updage script to run ci correctly

chat-application/lib/dialogs/user.dart, chat-application/lib/store/user.dart, chat-application/lib/widgets/avatar.dart, chat-application/lib/widgets/chat/main.dart, chat-application/lib/widgets/chat/widgets/flyer_user_avatar.dart, chat-application/lib/widgets/update_user/name_field.dart, chat-application/lib/widgets/update_user/update_user.dart
Design vraiment simple, il faudra réfléchir à quelque chose de plus joli et élaboré par la suite, pour l'instant on peut voir la photo et le nom, ça suffit.
J'en ai profiter pour enlever la photo en haut a gauche et mettre un icon menu à la place (plus clair, et puis c'était pratique, comme ça toutes les photos on la même action qui est de montrer le modal)
=> feat: simple modal to display name and photo

chat-application/lib/dialogs/user.dart, chat-application/lib/main.dart, chat-application/lib/message.dart, chat-application/lib/network/http_connection.dart, chat-application/lib/store/group_user.dart, chat-application/lib/store/user.dart, chat-application/lib/widgets/agreements.dart, chat-application/lib/widgets/avatar.dart, chat-application/lib/widgets/chat/main.dart, chat-application/lib/widgets/chat/widgets/flyer_chat.dart, chat-application/lib/widgets/chat/widgets/flyer_user_avatar.dart, chat-application/lib/widgets/update_user/name_field.dart, chat-application/lib/widgets/update_user/photo_field.dart, chat-application/lib/widgets/update_user/update_user.dart
User now have to upload a profil before entering the chat
=> feat: force user to upload their profil

chat-application/ios/Podfile.lock, chat-application/lib/dialogs/user.dart, chat-application/lib/widgets/update_user/name_field.dart, chat-application/lib/widgets/update_user/photo_field.dart, chat-application/pubspec.lock, chat-application/pubspec.yaml
Les images faisaient 2Mb et plus, maintenant ça descend à moins de 0.5Mb, c'est bien mieux 👍 Pas de perte de qualité visible.
=> feat: add compression image algorithm

chat-application/lib/dialogs/user.dart, chat-application/lib/dialogs/user_actions.dart, chat-application/lib/store/user.dart, chat-application/lib/widgets/avatar.dart, chat-application/lib/widgets/update_user/photo_field.dart, chat-application/lib/widgets/update_user/update_user.dart
=> feat: use relative path instead of absolute

chat-application/lib/store/user.dart, chat-application/pubspec.yaml, chat-backend/websocket/on-connect/__tests__/app.test.js, chat-backend/websocket/on-connect/app.js
=> 416 enlever notification onconnect

chat-application/lib/widgets/update_user/photo_field.dart
=> fix: returns uncompressed file if error

chat-backend/schedule/check-users-last-activity/__tests__/app.test.js, chat-backend/schedule/check-users-last-activity/app.js, chat-backend/template.yaml
=> feat: remove user from group after 3 days

chat-backend/schedule/check-users-last-activity/__tests__/app.test.js, chat-backend/schedule/check-users-last-activity/app.js
=> feat: remove users from group after one week

chat-backend/schedule/check-users-last-activity/__tests__/app.test.js, chat-backend/schedule/check-users-last-activity/app.js, chat-backend/template.yaml
This reverts commit 9f226563fffbe3f8d56b570d91e61e2c64b9526f.
=> Revert "feat: remove user from group after 3 days of inactivity (#428)"

chat-backend/chat-backend-package/src/__tests__/get-user-data.test.js, chat-backend/chat-backend-package/src/get-user-data.js, chat-backend/http/post/other-action/src/__tests__/start-typing.test.js, chat-backend/http/post/other-action/src/start-typing.js, chat-backend/http/post/text-message/__tests__/app.test.js, chat-backend/http/post/text-message/app.js, chat-backend/template.yaml
feat: send message in notification
=> feat: send message in notification

chat-application/lib/dialogs/change_group.dart, chat-application/lib/widgets/chat/main.dart
=> feat: add dialog to confirm to change group

agreements/credits/fr, agreements/privacy-policy/en, agreements/privacy-policy/fr
=> feat: update agreements

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/operation.md, .github/ISSUE_TEMPLATE/question.md
=> feat: update issue templates

.github/ISSUE_TEMPLATE/operation.md, .github/ISSUE_TEMPLATE/question.md, chat-backend/chat-backend-package/__tests__/index.test.js, chat-backend/chat-backend-package/index.js, chat-backend/chat-backend-package/src/__tests__/leave-group.test.js, chat-backend/chat-backend-package/src/helpers/__tests__/get-group-metadata.test.js, chat-backend/chat-backend-package/src/helpers/__tests__/get-group-users.test.js, chat-backend/chat-backend-package/src/helpers/get-group-metadata.js, chat-backend/chat-backend-package/src/helpers/get-group-users.js, chat-backend/chat-backend-package/src/leave-group.js, chat-backend/http/post/change-group/src/__tests__/create-group.test.js, chat-backend/http/post/change-group/src/__tests__/find-group.test.js, chat-backend/http/post/change-group/src/__tests__/join-group.test.js, chat-backend/http/post/change-group/src/create-group.js, chat-backend/http/post/change-group/src/find-group.js, chat-backend/http/post/change-group/src/join-group.js, chat-backend/http/post/upload-user/app.js, chat-backend/jest.config.js, chat-backend/samconfig.toml, chat-backend/schedule/check-users-last-activity/__tests__/app.test.js, chat-backend/schedule/check-users-last-activity/app.js, chat-backend/template.yaml
=> 438 only open group when there are five users
